##### One-dimensional arrays can be indexed, sliced and iterated over, much like lists and other Python sequences.

In [1]:
import numpy as np

In [2]:
a = np.arange(10)**3
a

array([  0,   1,   8,  27,  64, 125, 216, 343, 512, 729], dtype=int32)

In [3]:
a[0]

0

In [4]:
a[2:5]

array([ 8, 27, 64], dtype=int32)

In [5]:
a[ : :-1] 

array([729, 512, 343, 216, 125,  64,  27,   8,   1,   0], dtype=int32)

In [6]:
for i in a:
    print(i**(1/3.))

0.0
1.0
2.0
3.0
3.9999999999999996
5.0
5.999999999999999
6.999999999999999
7.999999999999999
8.999999999999998


###### Multidimensional arrays can have one index per axis. These indices are given in a tuple separated by commas:

In [20]:
def f(x,y):
    return x+y
b = np.fromfunction(f,(5,4),dtype=int)
b

array([[0, 1, 2, 3],
       [1, 2, 3, 4],
       [2, 3, 4, 5],
       [3, 4, 5, 6],
       [4, 5, 6, 7]])

In [21]:
 b[2,3]

5

In [22]:
b[0:5, 1]                       # each row in the second column of b

array([1, 2, 3, 4, 5])

In [23]:
b[ : ,1]                        # equivalent to the previous example

array([1, 2, 3, 4, 5])

In [24]:
b[1:3, : ]                      # each column in the second and third row of b

array([[1, 2, 3, 4],
       [2, 3, 4, 5]])

In [26]:
b[-1]                                  # the last row. Equivalent to b[-1,:]

array([4, 5, 6, 7])

In [27]:
b

array([[0, 1, 2, 3],
       [1, 2, 3, 4],
       [2, 3, 4, 5],
       [3, 4, 5, 6],
       [4, 5, 6, 7]])

In [28]:
b[-1,-1]

7

In [29]:
b

array([[0, 1, 2, 3],
       [1, 2, 3, 4],
       [2, 3, 4, 5],
       [3, 4, 5, 6],
       [4, 5, 6, 7]])

##### Iterating over multidimensional arrays is done with respect to the first axis:

In [32]:
for row in b:
    print(row)

[0 1 2 3]
[1 2 3 4]
[2 3 4 5]
[3 4 5 6]
[4 5 6 7]


In [33]:
b[-1,-2]

6