#### Changing the shape of an array

An array has a shape given by the number of elements along each axis:

In [2]:
import numpy as np

In [4]:
a = np.floor(10*np.random.random((3,4)))
a

array([[8., 9., 7., 0.],
       [4., 4., 8., 9.],
       [9., 7., 3., 8.]])

In [6]:
a.shape

(3, 4)

In [8]:
a.ravel()  # returns the array, flattened


array([8., 9., 7., 0., 4., 4., 8., 9., 9., 7., 3., 8.])

In [10]:
 a.reshape(6,2)  # returns the array with a modified shape

array([[8., 9.],
       [7., 0.],
       [4., 4.],
       [8., 9.],
       [9., 7.],
       [3., 8.]])

In [12]:
a.T  # returns the array, transposed

array([[8., 4., 9.],
       [9., 4., 7.],
       [7., 8., 3.],
       [0., 9., 8.]])

In [14]:
a.T.shape

(4, 3)

In [16]:
a.shape

(3, 4)

In [18]:
a.reshape(3,-1)


array([[8., 9., 7., 0.],
       [4., 4., 8., 9.],
       [9., 7., 3., 8.]])

In [22]:
a.resize((2,6))
a

array([[8., 9., 7., 0., 4., 4.],
       [8., 9., 9., 7., 3., 8.]])

#### Stacking together different arrays¶

Several arrays can be stacked together along different axes:

In [24]:
a = np.floor(10*np.random.random((2,2)))
a

array([[9., 6.],
       [6., 1.]])

In [27]:
b = np.floor(10*np.random.random((2,2)))
b


array([[3., 3.],
       [9., 3.]])

In [29]:
np.vstack((a,b))

array([[9., 6.],
       [6., 1.],
       [3., 3.],
       [9., 3.]])

In [31]:
 np.hstack((a,b))

array([[9., 6., 3., 3.],
       [6., 1., 9., 3.]])

The function column_stack stacks 1D arrays as columns into a 2D array. It is equivalent to hstack only for 2D arrays:

In [34]:
from numpy import newaxis
np.column_stack((a,b))     # with 2D arrays

array([[9., 6., 3., 3.],
       [6., 1., 9., 3.]])

In [37]:
a = np.array([4.,2.])
b = np.array([3.,8.])
np.column_stack((a,b))     # returns a 2D array

array([[4., 3.],
       [2., 8.]])

In [39]:
np.hstack((a,b))           # the result is different

array([4., 2., 3., 8.])

In [41]:
a[:,newaxis]               # this allows to have a 2D columns vector

array([[4.],
       [2.]])

In [43]:
np.column_stack((a[:,newaxis],b[:,newaxis]))

array([[4., 3.],
       [2., 8.]])

In [45]:
np.hstack((a[:,newaxis],b[:,newaxis]))   # the result is the same

array([[4., 3.],
       [2., 8.]])

On the other hand, the function row_stack is equivalent to vstack for any input arrays. In general, for arrays of with more than two dimensions, hstack stacks along their second axes, vstack stacks along their first axes, and concatenate allows for an optional arguments giving the number of the axis along which the concatenation should happen.

##### Note:

In complex cases, r_ and c_ are useful for creating arrays by stacking numbers along one axis. They allow the use of range literals (“:”)

In [47]:
np.r_[1:4,0,4]

array([1, 2, 3, 0, 4])

In [49]:
np.c_[np.array([1,2,3]), np.array([4,5,6])]

array([[1, 4],
       [2, 5],
       [3, 6]])

In [51]:
np.c_[np.array([[1,2,3]]), 0, 0, np.array([[4,5,6]])]

array([[1, 2, 3, 0, 0, 4, 5, 6]])

In [55]:
x = np.arange(16.0).reshape(4, 4)
print(x,"\n")
np.vsplit(x, 2)

[[ 0.  1.  2.  3.]
 [ 4.  5.  6.  7.]
 [ 8.  9. 10. 11.]
 [12. 13. 14. 15.]] 



[array([[0., 1., 2., 3.],
        [4., 5., 6., 7.]]), array([[ 8.,  9., 10., 11.],
        [12., 13., 14., 15.]])]

In [57]:
np.vsplit(x, np.array([3, 6]))

[array([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.]]),
 array([[12., 13., 14., 15.]]),
 array([], shape=(0, 4), dtype=float64)]

#### Split
Split an array into multiple sub-arrays.

Please refer to the split documentation. The only difference between these functions is that array_split allows indices_or_sections to be an integer that does not equally divide the axis. For an array of length l that should be split into n sections, it returns l % n sub-arrays of size l//n + 1 and the rest of size l//n.

In [60]:
x = np.arange(8.0)
np.array_split(x, 3)

[array([0., 1., 2.]), array([3., 4., 5.]), array([6., 7.])]