When operating and manipulating arrays, their data is sometimes copied into a new array and sometimes not. This is often a source of confusion for beginners. There are three cases:

In [1]:
import numpy as np

#### No Copy at All
Simple assignments make no copy of array objects or of their data.

In [2]:
a = np.arange(12)
b = a            # no new object is created    
b is a           # a and b are two names for the same ndarray object

True

In [6]:
b.shape  

(4, 3)

In [22]:
b.shape=3,2,2        # changes the shape of a
b

array([[[ 0,  1],
        [ 2,  3]],

       [[ 4,  5],
        [ 6,  7]],

       [[ 8,  9],
        [10, 11]]])

In [23]:
b.reshape(4,3)

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

#### View or Shallow Copy

In [24]:
c = a.view()
c

array([[[ 0,  1],
        [ 2,  3]],

       [[ 4,  5],
        [ 6,  7]],

       [[ 8,  9],
        [10, 11]]])

In [30]:
c is a

False

In [33]:
x = np.arange(3)
y = np.arange(3)

In [35]:
y.base is x

False

In [36]:
c.base is a # c is a view of the data owned by a

True

In [38]:
c

array([[[ 0,  1],
        [ 2,  3]],

       [[ 4,  5],
        [ 6,  7]],

       [[ 8,  9],
        [10, 11]]])

In [40]:
c[0,1] = 256   # a's data changes
c

array([[[  0,   1],
        [256, 256]],

       [[  4,   5],
        [  6,   7]],

       [[  8,   9],
        [ 10,  11]]])

In [41]:
c

array([[[  0,   1],
        [256, 256]],

       [[  4,   5],
        [  6,   7]],

       [[  8,   9],
        [ 10,  11]]])

In [43]:
a

array([[[  0,   1],
        [256, 256]],

       [[  4,   5],
        [  6,   7]],

       [[  8,   9],
        [ 10,  11]]])

In [44]:
b

array([[[  0,   1],
        [256, 256]],

       [[  4,   5],
        [  6,   7]],

       [[  8,   9],
        [ 10,  11]]])

In [51]:
s = a[ : , 1:3]               # spaces added for clarity; could also be written "s = a[:,1:3]"
s[:] = 100                    # s[:] is a view of s. Note the difference between s=10 and s[:]=10
s

array([[[100, 100]],

       [[100, 100]],

       [[100, 100]]])

#### Deep Copy
The copy method makes a complete copy of the array and its data.

In [45]:
d = a.copy() # a new array object with new data is created
d is a

False

In [46]:
d.base is a                           # d doesn't share anything with a

False

In [47]:
d[0,0] = 9999
d

array([[[9999, 9999],
        [ 256,  256]],

       [[   4,    5],
        [   6,    7]],

       [[   8,    9],
        [  10,   11]]])

In [48]:
a

array([[[  0,   1],
        [256, 256]],

       [[  4,   5],
        [  6,   7]],

       [[  8,   9],
        [ 10,  11]]])

## Functions and Methods Overview
Here is a list of some useful NumPy functions and methods names ordered in categories. See Routines for the full list.

#### Array Creation
arange, array, copy, empty, empty_like, eye, fromfile, fromfunction, identity, linspace, logspace, mgrid, ogrid, ones, ones_like, r, zeros, zeros_like
#### Conversions
ndarray.astype, atleast_1d, atleast_2d, atleast_3d, mat
#### Manipulations
array_split, column_stack, concatenate, diagonal, dsplit, dstack, hsplit, hstack, ndarray.item, newaxis, ravel, repeat, reshape, resize, squeeze, swapaxes, take, transpose, vsplit, vstack
#### Questions
all, any, nonzero, where
#### Ordering
argmax, argmin, argsort, max, min, ptp, searchsorted, sort
#### Operations
choose, compress, cumprod, cumsum, inner, ndarray.fill, imag, prod, put, putmask, real, sum
#### Basic Statistics
cov, mean, std, var
#### Basic Linear Algebra
cross, dot, outer, linalg.svd, vdot