#### Linear Algebra
Work in progress. Basic linear algebra to be included here.

#### Simple Array Operations

In [1]:
import numpy as np

In [2]:
a = np.array([[1.0, 2.0], [3.0, 4.0]])
a

array([[1., 2.],
       [3., 4.]])

In [3]:
a.transpose()

array([[1., 3.],
       [2., 4.]])

In [4]:
a.T

array([[1., 3.],
       [2., 4.]])

In [12]:
np.linalg.inv(a)

array([[ 0.6, -0.7],
       [-0.2,  0.4]])

In [13]:
from numpy.linalg import inv
a = np.array([[4,7], [2, 6]])
ainv = inv(a)

![](https://lh3.googleusercontent.com/-KJ2ZOE9awz4/XTfHDTssSiI/AAAAAAAAgFs/u8Z2z76FXdQW_ia55WMHTT0ebeXxXhmUACK8BGAs/s0/2019-07-23.png)

In [14]:
ainv

array([[ 0.6, -0.7],
       [-0.2,  0.4]])

In [15]:
u = np.eye(2) # unit 2x2 matrix; "eye" represents "I"
u

array([[1., 0.],
       [0., 1.]])

In [16]:
j = np.array([[0.0, -1.0], [1.0, 0.0]])
j @ j        # matrix product

array([[-1.,  0.],
       [ 0., -1.]])

In [23]:
a = np.array([[3,1],
              [4,5]])
print(a)
np.trace(a)  # trace

[[3 1]
 [4 5]]


8

In [24]:
a

array([[3, 1],
       [4, 5]])

In [25]:
y = np.array([[5.], [7.]])
np.linalg.solve(a, y)

array([[1.63636364],
       [0.09090909]])

In [26]:
a = np.array([[3,1], [1,2]])
b = np.array([9,8])
x = np.linalg.solve(a, b)
x

array([2., 3.])

In [30]:
np.allclose(np.dot(a, x), b)

True

https://en.wikipedia.org/wiki/Linear_equation
    
# One Varaiable:
        aX+b= 0
        
        x = -b/a

# Two Variables
        
        ax+bx+c=0
        
        x(a+b)+c=0
        1/x = -((a+b)+c)
