<a href="https://colab.research.google.com/github/reddyprasade/Numpy-with-Python/blob/master/Linear_Algebra_with_Python.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>


## Python and Pip

If you are using your own PC, Anaconda is recommended. But at least, please download [Python](https://www.python.org/downloads/) and [Pip](https://pip.pypa.io/en/stable/installing/). 


## Libraries

We'll be working with `numpy` and `scipy`, so make sure to install them. Pull up your terminal and insert the following: 

```
pip3 install scipy
pip3 install numpy
```

## Vectors

A vector is typically an ordered tuple of numbers which have both a magnitude and direction. r. 

With that said, we <i>can</i> represent a vector with a list, for example: 

In [0]:
A = [2.0, 3.0, 5.0]

Now, let's write this same vector with `numpy` instead:

In [0]:
v = np.array([2.0, 3.0, 5.0])

### What is a Norm? 

A norm just refers to the magnitude of a vector, and is denoted with ||u||. With numpy and scipy, we can do calculate the norm as follows: 

In [0]:
import numpy as np
v = np.array([1,2,3,4])
nln.norm(v)

5.4772255750516612

The actual formula looks like: 

$$ ||v|| = \sqrt{v_1^2 + ... + v_n^2} $$

## Matrices

A Matrix is a 2D array that stores real or complex numbers.  You can use numpy to create matrices:

In [0]:
matrix1 = np.matrix(
    [[0, 4],
     [2, 0]]
)
matrix2 = np.matrix(
    [[-1, 2],
     [1, -2]]
)

# 1.0 Linear Equations

## Gauss-Jordan Elimination

Gaussian Elimination helps to put a matrix in row echelon form, while Gauss-Jordan Elimination puts a matrix in reduced row echelon form?

## Solving Systems of Equations

Consider a set of m linear equations in n unknowns:

...

We can let:

...

And re-write the system: 

```
Ax = b
```
This reduces the problem to a matrix equation and now we can solve the system to find $A^{-1}$.


### Systems of Equations with Python


In [0]:
A = np.array([ [3,-9], [2,4] ])
b = np.array([-42,2])

Now, we can use the `linalg.solve()` function to solve the x and y values. Note that these values will be


In [0]:
np.linalg.solve(A,b)

array([-5.,  3.])

# 2.0 Linear Transformations

## Matrix Operations

What makes matrices particularly useful is the fact that we can perform operations on them. While it won't be necessarily intuitive why these operations are important right now, it will become obvious in later content.

### Addition

Matrix addition works very similarlty to normal addition. You simply add the corresponding spots together. 


In [0]:
matrix1 + matrix2

matrix([[-1,  6],
        [ 3, -2]])

### Multiplication

To multiply two matrices with numpy, you can use the `np.dot` method: 


In [0]:
np.dot(matrix1, matrix2)

matrix([[ 4, -8],
        [-2,  4]])

Or, simply, you can do:

In [0]:
matrix1 * matrix2

matrix([[ 4, -8],
        [-2,  4]])

The dot product is an operation that takes two coordinate vectors of equal size and returns a single number. The result is calculated by multiplying corresponding entries and adding up those products. 

### Identity Matrix

A Diagonal Matrix is an n x n matrix with 1s on the diagonal from the top left to the bottom right, such as 

``` 
[[ 1., 0., 0.],
[ 0., 1., 0.],
[ 0., 0., 1.]]
```

We can generate diagonal matrices with the `eye()` function in Python: 


In [0]:
np.eye(4)

array([[ 1.,  0.,  0.,  0.],
       [ 0.,  1.,  0.,  0.],
       [ 0.,  0.,  1.,  0.],
       [ 0.,  0.,  0.,  1.]])

When a matrix is multiplied by its inverse, the result is the identity matrix. It's important to note that only square matrices have inverses!

### Inverse Matrices

The matrix A is invertible if there exists a matrix A<sub>-1</sub> such that

A<sub>-1</sub>A = I and AA<sub>-1</sub> = I

Multiplying inverse matrix is like the division; it’s simply the reciprocal function of multiplication. Let’s say here is a square matrix A, then multiplying its inversion gives the identity matrix I.

We can get the inverse matrix with numpy: 

In [0]:
inverse = np.linalg.inv(matrix1)
print(inverse)

[[ 0.    0.5 ]
 [ 0.25  0.  ]]


# 3.0 Orthogonality and Least Squares


## QR Decomposition with Gram-Schmidt


QR decomposition (also called a QR factorization) of a matrix is a decomposition of a matrix A into a product A = QR of an orthogonal matrix Q and an upper triangular matrix R. QR decomposition is often used to solve the linear least squares problem and is the basis for a particular eigenvalue algorithm, the QR algorithm.

In [0]:
A = np.matrix([[1,1,0], [1,0,1], [0,1,1]])

In [0]:
Q,R = np.linalg.qr(A)

In [0]:
Q

matrix([[-0.70710678,  0.40824829, -0.57735027],
        [-0.70710678, -0.40824829,  0.57735027],
        [-0.        ,  0.81649658,  0.57735027]])

In [0]:
R

matrix([[-1.41421356, -0.70710678, -0.70710678],
        [ 0.        ,  1.22474487,  0.40824829],
        [ 0.        ,  0.        ,  1.15470054]])

# 4.0 Determinants

### Trace and Determinant

The trace of a matrix A is the sum of its diagonal elements. It's important because it's an invariant of a matrix under change of basis and it defines a matrix norm. 

In Python, this can be done with the `numpy` module: 

In [0]:
print(np.trace(matrix1))

0


which in this case is just `0`. 

The determinant of a matrix is defined to be the alternating sum of permutations of the elements of a matrix. The formula is as follows:

\begin{bmatrix} 
    a      & b  \\
    c      & d  \\
\end{bmatrix}



$$ = ad - bc $$

In python, you can use the following function:

In [0]:
det = np.linalg.det(matrix1)
print(det)

-8.0


Note that an n×n matrix A is invertible $\iff$ det(A) $\ne$ 0.

## Matrix Types



### Transpose

The transpose of a matrix is another operation that can be accomplished with `numpy`. Its importance isn't so obvious as first, but they're used to <HERE>. Now, let's take a look at an example. Given the matrix below, let's find what its transpose looks like. 

In [0]:
a = np.array([[1, 2], [3, 4]])
a

array([[1, 2],
       [3, 4]])

Notice the the 2 and 3 flipped positions. The transpose essentially flips the positions of a matrix in a particular way. 

In [0]:
a.transpose()

array([[1, 3],
       [2, 4]])

So what does that look like when we have a matrix that's not 2x2 dimensions? 

In [0]:
a = np.array([[1, 2, 3], [4, 5, 6]])
a

array([[1, 2, 3],
       [4, 5, 6]])

The number of dimensions is now flipped as well. Instead of three columns, we now have two. And instead of two rows, we now have three. 

In [0]:
a.transpose()

array([[1, 4],
       [2, 5],
       [3, 6]])

# 5.0 Eigenvalues & Eigenvectors

Let A be an `n x n` matrix. The number &lambda; is an eigenvalue of `A` if there exists a non-zero vector `C` such that

Av = &lambda;v

In this case, vector `v` is called an eigenvector of `A` corresponding to &lambda;. You can use numpy to calculate the eigenvalues and eigenvectors of a matrix: 

In [0]:
eigenvecs, eigvals = np.linalg.eigvals(matrix1)
print(eigenvecs, eigvals)

2.82842712475 -2.82842712475


It's important to note that eigenvectors do not change direction in the transformation of the matrix.
