### Indexing on ndarrays

<p id="index-0"><a class="reference internal" href="../reference/generated/numpy.ndarray.html#numpy.ndarray" title="numpy.ndarray"><code class="xref py py-class docutils literal notranslate"><span class="pre">ndarrays</span></code></a> can be indexed using the standard Python
<code class="docutils literal notranslate"><span class="pre">x[obj]</span></code> syntax, where <em>x</em> is the array and <em>obj</em> the selection
There are different kinds of indexing available depending on <em>obj</em:
basic indexing, advanced indexing and field access.<


![](https://miro.medium.com/v2/resize:fit:1400/1*4xpufyWZWcIbabsOHVlc4g.png)/p>

In [2]:
import numpy as np

In [3]:
a = np.arange(1,6)
a

array([1, 2, 3, 4, 5])

In [4]:
a[1] # Indexing

2

In [5]:
a[2:4] # Postive Slice

array([3, 4])

In [6]:
a[-2:] # Nagative Slice

array([4, 5])

In [7]:
a[::2] # extended Slice

array([1, 3, 5])

In [11]:
a[[2,3,4]] # Facncy Index

array([3, 4, 5])

In [12]:
x = np.arange(10) # Vector

x.shape

(10,)

In [13]:
x.ndim

1

In [ ]:
1 * 10 = 10
10 * 1 = 10
5 * 2 = 10 
2 * 5 = 10


In [14]:
x.shape = (2,5) # Reshaping

In [15]:
x

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [16]:
x.ndim

2

#### Indexing

In [17]:
x[1]

array([5, 6, 7, 8, 9])

In [18]:
x[1][0]

5

In [19]:
x[1,0]

5

In [20]:
_3d = np.array(np.arange(1,25))
_3d

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24])

In [21]:
_3d.shape

(24,)

In [22]:
_3d.ndim

1

In [23]:
# 2 D Array Covertion 
12 * 2
2 * 12
24 * 1
1 * 24
6 * 4
4 * 6 
8 * 3
3 * 8 

24

In [ ]:
# 3 D Array Conversation

6 * 2 * 2
2 * 6 * 2
12 * 2 * 1


In [24]:
_3d_convert = _3d.reshape(6,2,2)
_3d_convert

array([[[ 1,  2],
        [ 3,  4]],

       [[ 5,  6],
        [ 7,  8]],

       [[ 9, 10],
        [11, 12]],

       [[13, 14],
        [15, 16]],

       [[17, 18],
        [19, 20]],

       [[21, 22],
        [23, 24]]])

In [25]:
_3d_convert.ndim

3

In [26]:
_3d_convert.shape

(6, 2, 2)

In [27]:
_3d_convert[0]

array([[1, 2],
       [3, 4]])

In [28]:
_3d_convert[0][1]

array([3, 4])

In [29]:
_3d_convert[0][1][1]

4

In [30]:
_3d_convert[0,1,1] 

4

#### Slicing and striding



<p>Basic slicing extends Python’s basic concept of slicing to N
dimensions. Basic slicing occurs when <em>obj</em> is a <a class="reference external" href="https://docs.python.org/3/library/functions.html#slice" title="(in Python v3.12)"><code class="xref py py-class docutils literal notranslate"><span class="pre">slice</span></code></a> object
(constructed by <code class="docutils literal notranslate"><span class="pre">start:stop:step</span></code> notation inside of brackets), an
integer, or a tuple of slice objects and integers. <a class="reference external" href="https://docs.python.org/3/library/constants.html#Ellipsis" title="(in Python v3.12)"><code class="xref py py-data docutils literal notranslate"><span class="pre">Ellipsis</span></code></a>
and <a class="reference internal" href="../reference/constants.html#numpy.newaxis" title="numpy.newaxis"><code class="xref py py-const docutils literal notranslate"><span class="pre">newaxis</span></code></a> objects can be interspersed with these as
well

<p id="index-1">The simplest case of indexing with <em>N</em> integers returns an <a class="reference internal" href="../reference/arrays.scalars.html#arrays-scalars"><span class="std std-ref">array
scalar</span></a> representing the corresponding item.  As in
Python, all indices are zero-based: for the <em>i</em>-th index <span class="math notranslate nohighlight"><span class="MathJax_Preview" style="color: inherit; display: none;"></span><span class="MathJax_SVG" id="MathJax-Element-1-Frame" tabindex="0" data-mathml="<math xmlns=&quot;http://www.w3.org/1998/Math/MathML&quot;><msub><mi>n</mi><mi>i</mi></msub></math>" role="presentation" style="font-size: 100%; display: inline-block; position: relative;"><svg xmlns:xlink="http://www.w3.org/1999/xlink" width="2.194ex" height="1.752ex" viewBox="0 -538 944.8 754.3" role="img" focusable="false" style="vertical-align: -0.503ex;" aria-hidden="true"><g stroke="currentColor" fill="currentColor" stroke-width="0" transform="matrix(1 0 0 -1 0 0)"><use xlink:href="#MJMATHI-6E" x="0" y="0"></use><use transform="scale(0.707)" xlink:href="#MJMATHI-69" x="849" y="-213"></use></g></svg><span class="MJX_Assistive_MathML" role="presentation"><math xmlns="http://www.w3.org/1998/Math/MathML"><msub><mi>n</mi><mi>i</mi></msub></math></span></span><script type="math/tex" id="MathJax-Element-1">n_i</script></span>,
the valid range is <span class="math notranslate nohighlight"><span class="MathJax_Preview" style="color: inherit; display: none;"></span><span class="MathJax_SVG" id="MathJax-Element-2-Frame" tabindex="0" data-mathml="<math xmlns=&quot;http://www.w3.org/1998/Math/MathML&quot;><mn>0</mn><mo>&amp;#x2264;</mo><msub><mi>n</mi><mi>i</mi></msub><mo>&amp;lt;</mo><msub><mi>d</mi><mi>i</mi></msub></math>" role="presentation" style="font-size: 100%; display: inline-block; position: relative;"><svg xmlns:xlink="http://www.w3.org/1999/xlink" width="11.562ex" height="2.25ex" viewBox="0 -752.3 4978.2 968.7" role="img" focusable="false" style="vertical-align: -0.503ex;" aria-hidden="true"><g stroke="currentColor" fill="currentColor" stroke-width="0" transform="matrix(1 0 0 -1 0 0)"><use xlink:href="#MJMAIN-30" x="0" y="0"></use><use xlink:href="#MJMAIN-2264" x="778" y="0"></use><g transform="translate(1834,0)"><use xlink:href="#MJMATHI-6E" x="0" y="0"></use><use transform="scale(0.707)" xlink:href="#MJMATHI-69" x="849" y="-213"></use></g><use xlink:href="#MJMAIN-3C" x="3057" y="0"></use><g transform="translate(4113,0)"><use xlink:href="#MJMATHI-64" x="0" y="0"></use><use transform="scale(0.707)" xlink:href="#MJMATHI-69" x="736" y="-213"></use></g></g></svg><span class="MJX_Assistive_MathML" role="presentation"><math xmlns="http://www.w3.org/1998/Math/MathML"><mn>0</mn><mo>≤</mo><msub><mi>n</mi><mi>i</mi></msub><mo>&lt;</mo><msub><mi>d</mi><mi>i</mi></msub></math></span></span><script type="math/tex" id="MathJax-Element-2">0 \le n_i < d_i</script></span> where <span class="math notranslate nohighlight"><span class="MathJax_Preview" style="color: inherit; display: none;"></span><span class="MathJax_SVG" id="MathJax-Element-3-Frame" tabindex="0" data-mathml="<math xmlns=&quot;http://www.w3.org/1998/Math/MathML&quot;><msub><mi>d</mi><mi>i</mi></msub></math>" role="presentation" style="font-size: 100%; display: inline-block; position: relative;"><svg xmlns:xlink="http://www.w3.org/1999/xlink" width="2.009ex" height="2.25ex" viewBox="0 -752.3 864.8 968.7" role="img" focusable="false" style="vertical-align: -0.503ex;" aria-hidden="true"><g stroke="currentColor" fill="currentColor" stroke-width="0" transform="matrix(1 0 0 -1 0 0)"><use xlink:href="#MJMATHI-64" x="0" y="0"></use><use transform="scale(0.707)" xlink:href="#MJMATHI-69" x="736" y="-213"></use></g></svg><span class="MJX_Assistive_MathML" role="presentation"><math xmlns="http://www.w3.org/1998/Math/MathML"><msub><mi>d</mi><mi>i</mi></msub></math></span></span><script type="math/tex" id="MathJax-Element-3">d_i</script></span> is the
<em>i</em>-th element of the shape of the array.  Negative indices are
interpreted as counting from the end of the array (<em>i.e.</em>, if
<span class="math notranslate nohighlight"><span class="MathJax_Preview" style="color: inherit; display: none;"></span><span class="MathJax_SVG" id="MathJax-Element-4-Frame" tabindex="0" data-mathml="<math xmlns=&quot;http://www.w3.org/1998/Math/MathML&quot;><msub><mi>n</mi><mi>i</mi></msub><mo>&amp;lt;</mo><mn>0</mn></math>" role="presentation" style="font-size: 100%; display: inline-block; position: relative;"><svg xmlns:xlink="http://www.w3.org/1999/xlink" width="6.455ex" height="2.25ex" viewBox="0 -752.3 2779.4 968.7" role="img" focusable="false" style="vertical-align: -0.503ex;" aria-hidden="true"><g stroke="currentColor" fill="currentColor" stroke-width="0" transform="matrix(1 0 0 -1 0 0)"><use xlink:href="#MJMATHI-6E" x="0" y="0"></use><use transform="scale(0.707)" xlink:href="#MJMATHI-69" x="849" y="-213"></use><use xlink:href="#MJMAIN-3C" x="1222" y="0"></use><use xlink:href="#MJMAIN-30" x="2278" y="0"></use></g></svg><span class="MJX_Assistive_MathML" role="presentation"><math xmlns="http://www.w3.org/1998/Math/MathML"><msub><mi>n</mi><mi>i</mi></msub><mo>&lt;</mo><mn>0</mn></math></span></span><script type="math/tex" id="MathJax-Element-4">n_i < 0</script></span>, it means <span class="math notranslate nohighlight"><span class="MathJax_Preview" style="color: inherit; display: none;"></span><span class="MathJax_SVG" id="MathJax-Element-5-Frame" tabindex="0" data-mathml="<math xmlns=&quot;http://www.w3.org/1998/Math/MathML&quot;><msub><mi>n</mi><mi>i</mi></msub><mo>+</mo><msub><mi>d</mi><mi>i</mi></msub></math>" role="presentation" style="font-size: 100%; display: inline-block; position: relative;"><svg xmlns:xlink="http://www.w3.org/1999/xlink" width="7.043ex" height="2.25ex" viewBox="0 -752.3 3032.6 968.7" role="img" focusable="false" style="vertical-align: -0.503ex;" aria-hidden="true"><g stroke="currentColor" fill="currentColor" stroke-width="0" transform="matrix(1 0 0 -1 0 0)"><use xlink:href="#MJMATHI-6E" x="0" y="0"></use><use transform="scale(0.707)" xlink:href="#MJMATHI-69" x="849" y="-213"></use><use xlink:href="#MJMAIN-2B" x="1167" y="0"></use><g transform="translate(2167,0)"><use xlink:href="#MJMATHI-64" x="0" y="0"></use><use transform="scale(0.707)" xlink:href="#MJMATHI-69" x="736" y="-213"></use></g></g></svg><span class="MJX_Assistive_MathML" role="presentation"><math xmlns="http://www.w3.org/1998/Math/MathML"><msub><mi>n</mi><mi>i</mi></msub><mo>+</mo><msub><mi>d</mi><mi>i</mi></msub></math></span></span><script type="math/tex" id="MathJax-Element-5">n_i + d_i</script></span>).</p>.</p>

In [3]:
x = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [5]:
x[1:7]

array([1, 2, 3, 4, 5, 6])

In [6]:
x[1:7:3]

array([1, 4])

In [7]:
x[-2:10]

array([8, 9])

In [9]:
x[-3:3:-1]

array([7, 6, 5, 4])

In [10]:
x = np.array([[[1],[2],[3]], [[4],[5],[6]]])
x

array([[[1],
        [2],
        [3]],

       [[4],
        [5],
        [6]]])

In [11]:
x.shape

(2, 3, 1)

In [13]:
x[1]

array([[4],
       [5],
       [6]])

In [14]:
x[1:2]

array([[[4],
        [5],
        [6]]])

##### Dimensional indexing tools

In [19]:
x[..., 0] # Ellipsis expands to the number of objects needed for the selection tuple to index all dimensions

array([[1, 2, 3],
       [4, 5, 6]])

In [20]:
x[:, :, 0]

array([[1, 2, 3],
       [4, 5, 6]])

Each `newaxis` object in the selection tuple serves to expand the dimensions of the resulting selection by one unit-length dimension.

In [21]:
x[:,np.newaxis,:,:].shape

(2, 1, 3, 1)

In [22]:
x[:, None, :, :].shape

(2, 1, 3, 1)

In [23]:
x[:, None, :, :]

array([[[[1],
         [2],
         [3]]],


       [[[4],
         [5],
         [6]]]])

In [24]:
x = np.arange(5)
x

array([0, 1, 2, 3, 4])

In [26]:
x[:,np.newaxis] # Convert 1 dim to 2 dim

array([[0],
       [1],
       [2],
       [3],
       [4]])

In [27]:
x[np.newaxis,:] 

array([[0, 1, 2, 3, 4]])

In [25]:
x[:,np.newaxis] + x[np.newaxis,:]

array([[0, 1, 2, 3, 4],
       [1, 2, 3, 4, 5],
       [2, 3, 4, 5, 6],
       [3, 4, 5, 6, 7],
       [4, 5, 6, 7, 8]])

In [28]:
x

array([0, 1, 2, 3, 4])

#### Advanced indexing 

1. Advanced Indexing is triggered when the selection object, obj, is a non-tuple sequence object, an ndarray (of data type integer or bool), or a tuple with at least one sequence object or ndarray (of data type integer or bool).
2. There are **two types of advanced indexing**: `integer` and `Boolean`.

##### Integer Advance Indexig

In [29]:
x = np.arange(10, 1, -1)
x

array([10,  9,  8,  7,  6,  5,  4,  3,  2])

In [30]:
x[np.array([3,3,1,8])] # array advanced indexing with integer

array([7, 7, 9, 2])

In [31]:
x[np.array([3,3,-3,8])]

array([7, 7, 4, 2])

In [32]:
x = np.array([[1, 2], [3, 4], [5, 6]])
x

array([[1, 2],
       [3, 4],
       [5, 6]])

In [33]:
x[np.array([1, -1])]

array([[3, 4],
       [5, 6]])

In [37]:
x[np.array([2])]

array([[5, 6]])

In [38]:
x[np.array([3, 4])]

IndexError: index 3 is out of bounds for axis 0 with size 3

In [39]:
y = np.arange(35).reshape(5, 7)
y

array([[ 0,  1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12, 13],
       [14, 15, 16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25, 26, 27],
       [28, 29, 30, 31, 32, 33, 34]])

In [41]:
y[np.array([0,2,4]),np.array([0,1,-1])]

array([ 0, 15, 34])

In [42]:
y[np.array([0,2,4]),np.array([0,1])]

IndexError: shape mismatch: indexing arrays could not be broadcast together with shapes (3,) (2,) 

In [43]:
y[np.array([0, 2, 4]), 1]  # 2 Row Selected in one column

array([ 1, 15, 29])

In [44]:
y[np.array([0, 2, 4])]  # Only Row Selction

array([[ 0,  1,  2,  3,  4,  5,  6],
       [14, 15, 16, 17, 18, 19, 20],
       [28, 29, 30, 31, 32, 33, 34]])

In [45]:
x = np.array([[ 0,  1,  2],
              [ 3,  4,  5],
              [ 6,  7,  8],
              [ 9, 10, 11]])
x

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [46]:
rows = np.array([[0, 0],
                 [3, 3]], dtype=np.intp)
rows

array([[0, 0],
       [3, 3]], dtype=int64)

In [47]:
columns = np.array([[0, 2],
                    [0, 2]], dtype=np.intp)

In [49]:
x[rows,columns]

array([[ 0,  2],
       [ 9, 11]])

In [50]:
rows = np.array([0, 3], dtype=np.intp)
columns = np.array([0, 2], dtype=np.intp)
rows[:, np.newaxis]

array([[0],
       [3]], dtype=int64)

In [51]:
x[rows[:, np.newaxis], columns]

array([[ 0,  2],
       [ 9, 11]])

In [52]:
x[np.ix_(rows, columns)]

array([[ 0,  2],
       [ 9, 11]])

In [59]:
a = np.array([0,10,20,30])
a

array([ 0, 10, 20, 30])

In [60]:
b =  np.array([0,1,2])

In [61]:
b

array([0, 1, 2])

In [62]:
y = a[:,np.newaxis] + b
y

array([[ 0,  1,  2],
       [10, 11, 12],
       [20, 21, 22],
       [30, 31, 32]])

![](images/newaxis.png)

##### Boolean array indexing

In [68]:
x = np.array([[1., 2.], [np.nan, 3.], [np.nan, np.nan]])#[np.nan, None]])
x

array([[ 1.,  2.],
       [nan,  3.],
       [nan, nan]])

In [69]:
x[~np.isnan(x)]

array([1., 2., 3.])

In [75]:
x = np.array([1., -1., -2., 3])
x

array([ 1., -1., -2.,  3.])

In [79]:
x<=1

array([ True,  True,  True, False])

In [80]:
x[x<=1]

array([ 1., -1., -2.])

In [73]:
x[x<10] +=20
x

array([21., 19., 18., 23.])

In [81]:
x = np.arange(35).reshape(5, 7)
x

array([[ 0,  1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12, 13],
       [14, 15, 16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25, 26, 27],
       [28, 29, 30, 31, 32, 33, 34]])

In [82]:
b = x > 20
b

array([[False, False, False, False, False, False, False],
       [False, False, False, False, False, False, False],
       [False, False, False, False, False, False, False],
       [ True,  True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True,  True,  True]])

In [90]:
b[:,5]

array([False, False, False,  True,  True])

In [88]:
x[b[:,0]]

array([[21, 22, 23, 24, 25, 26, 27],
       [28, 29, 30, 31, 32, 33, 34]])

In [91]:
x = np.array([[0, 1], [1, 1], [2, 2]])
rowsum = x.sum(-1)
rowsum

array([1, 2, 4])

In [93]:
x[rowsum <=2,:]

array([[0, 1],
       [1, 1]])