## Copies and views

### Copy

* When a `new array` is created by duplicating the data buffer as well as the metadata, it is called a `copy`.
* Changes made to the copy do not reflect on the original array.
* Making a copy is slower and memory-consuming but sometimes necessary.
* A copy can be forced by using `ndarray.copy`.

In [9]:
import numpy as np

In [10]:
a = np.arange(10).reshape(5,2)  # Orginal Array 
a

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

In [11]:
b = a  # Copy array
b

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

In [12]:
b[0][0] = 100
b

array([[100,   1],
       [  2,   3],
       [  4,   5],
       [  6,   7],
       [  8,   9]])

In [13]:
a

array([[100,   1],
       [  2,   3],
       [  4,   5],
       [  6,   7],
       [  8,   9]])

* Views are created when elements can be addressed with offsets and strides in the original array. Hence, basic indexing always creates views.

In [14]:
x = np.arange(10)
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [17]:
y = x[1:3]
y

array([1, 2])

In [18]:
x[1:3] = [10, 11]
x

array([ 0, 10, 11,  3,  4,  5,  6,  7,  8,  9])

In [19]:
y

array([10, 11])

![](https://media.geeksforgeeks.org/wp-content/uploads/shallow-copy.jpg)

* A deep copy creates a new compound object before inserting copies of the items found in the original into it in a recursive manner.
![](https://media.geeksforgeeks.org/wp-content/uploads/deep-copy.jpg)

In [24]:
original_array = np.array([5, 10, 15, 20,25])

In [25]:
# Creating a numpy array 
array = np.array([4.54, 6.99, 8.42, 10.87, 16.94])
print("Original array:\n",array)


Original array:
 [ 4.54  6.99  8.42 10.87 16.94]


In [26]:
copy_array = np.copy(array)
print("After getting the copied array:\n",copy_array)

After getting the copied array:
 [ 4.54  6.99  8.42 10.87 16.94]


In [27]:
# Creating a 3-D numpy array
array = np.array([[12,18,44], [66,37,89],[31,47,88]])
print("Original array:\n",array)
 
# Use numpy.copy() function
# Use multi-dimensional array
copy_array = np.copy(array)
print("After getting the copied multi-dimensional array:\n",copy_array)

Original array:
 [[12 18 44]
 [66 37 89]
 [31 47 88]]
After getting the copied multi-dimensional array:
 [[12 18 44]
 [66 37 89]
 [31 47 88]]


In [28]:
# Using assignment operator
copy_array = original_array

# Let's change the value.
original_array[0] = 77
print("After getting the copied array:\n",copy_array)

After getting the copied array:
 [77 10 15 20 25]


In [29]:
original_array

array([77, 10, 15, 20, 25])

In [30]:
# Creating a numpy array
array = np.array([0,3,5,7,9,11,13,15,17,19])
print("Original array:\n",array)


Original array:
 [ 0  3  5  7  9 11 13 15 17 19]


In [31]:
# Creating an empty Numpy array
# Similar to array
copy1 = np.empty_like(array)
copy1

array([-1030792151,  1074931957, -1889785610,  1075574210,  1030792151,
        1075894026, -1546188227,  1076215152,  -687194767,  1076949155])

In [32]:
# Now assign array to copy
copy1[:] = array
print("Copy of the given array:\n",copy1)

Copy of the given array:
 [ 0  3  5  7  9 11 13 15 17 19]


In [33]:
x = np.ones((2, 3))
x

array([[1., 1., 1.],
       [1., 1., 1.]])

In [34]:
y = x.T
y

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

In [35]:
z = y.copy()
z

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

In [36]:
z[0][0]

1.0

In [37]:
z[0][0] = 100

In [38]:
z

array([[100.,   1.],
       [  1.,   1.],
       [  1.,   1.]])

In [39]:
y

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

In [40]:
x

array([[1., 1., 1.],
       [1., 1., 1.]])

In [41]:
y.view()

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

In [42]:
p = y.view()
p

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

In [43]:
p.shape

(3, 2)

In [44]:
p.shape= 6 

AttributeError: Incompatible shape for in-place modification. Use `.reshape()` to make a copy with the desired shape.